# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 983ca909078166e39b6e40937dbbadfa3436259926081f9dc96aef55e216cbcaeb15c2130a8aa38a9c5a2b8cfecf91a5bf9c624701fc65ee0dda436e3690b8a2

test:
  secret_key_base: d10cfe729e1d6aa706674160885b9a1c7fe81f05d41fc2d2e84c167ce7f89d0c467f1f01040496da023c0f9df517ed2dcb75ba17ec52c523acdedbc4cc98edab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
